package com.frpdroid.app

/**
 * UI 文案字典：zh/en 双语。`T(str)` 按当前语言取词。
 */
class T(val zh: Map<String, String>, val en: Map<String, String>) {
    companion object {
        val zhMap: Map<String, String> = mapOf(
            "home" to "主页", "config" to "配置", "overview" to "概览", "log" to "日志",
            "settings" to "设置", "running" to "运行中", "stopped" to "已停止", "start" to "启动",
            "stop" to "停止", "server" to "FRP服务器", "address" to "地址", "port" to "端口",
            "token" to "令牌", "token_opt" to "令牌（可选）", "user" to "用户", "user_opt" to "用户（可选）",
            "proxies" to "代理", "visitors" to "访问者", "add" to "添加", "no_proxy" to "暂无代理",
            "no_visitor" to "暂无访问者", "visitor_hint" to "访问 stcp/xtcp 服务？请在「访问者」中添加",
            "add_hint" to "点击右下角 + 按钮添加", "auto_start" to "开机自启", "language" to "语言",
            "english" to "English", "clear" to "清空", "type" to "类型", "local_ip" to "本地IP",
            "local_port" to "本地端口", "remote_port" to "远程端口", "cancel" to "取消",
            "add_proxy" to "添加代理", "add_visitor" to "添加访问者", "output" to "输出",
            "launcher" to "FrpDroid", "tap_start" to "点击启动远程隧道", "version" to "版本",
            "about" to "关于", "notif" to "通知栏", "notif_on" to "开启通知", "import" to "导入",
            "theme" to "深色模式",
            "export" to "导出", "export_ok" to "配置已导出到", "import_ok" to "导入成功",
            "import_fail" to "文件格式错误或无法解析", "secret_key" to "密钥", "custom_domains" to "自定义域名",
            "multiplexer" to "多路复用", "server_name" to "服务名称", "bind_addr" to "绑定地址",
            "bind_port" to "绑定端口", "fallback_to" to "回退访问者", "fallback_timeout" to "回退超时(ms)", "keep_open" to "保持隧道开启", "plugin" to "插件",
            "unix_path" to "Unix套接字路径", "local_path" to "本地路径", "strip_prefix" to "Strip前缀",
            "http_user" to "HTTP用户", "http_password" to "HTTP密码", "local_addr" to "本地地址",
            "crt_path" to "证书路径", "key_path" to "密钥路径", "host_rewrite" to "Host重写",
            "req_headers" to "请求头(key=val)", "metadatas" to "元数据(key=val)（可选）", "tcp" to "TCP", "udp" to "UDP", "http" to "HTTP",
            "https" to "HTTPS", "tcpmux" to "TCPMux", "stcp" to "STCP", "xtcp" to "XTCP",
            "none" to "无", "unix_domain_socket" to "UnixSocket", "static_file" to "静态文件",
            "https2http" to "HTTPS→HTTP", "proxy_tab" to "代理", "visitor_tab" to "访问者",
            "save" to "保存", "no_logs" to "暂无日志", "traffic" to "流量", "download" to "下载",
            "upload" to "上传", "reset" to "重置", "ok" to "好", "author" to "作者",
            "frp_version" to "frp 版本", "cf_version" to "Cloudflare 版本", "saved" to "已保存",
            "edit_proxy" to "编辑代理", "edit_visitor" to "编辑访问者", "select_server" to "选择服务器",
            "new_server" to "新增服务器", "server_label" to "服务器名称", "current_server" to "当前服务器",
            "delete_server" to "删除", "import_as_new" to "作为新服务器导入", "rename_server" to "重命名服务器",
            "import_overwrite" to "覆盖当前服务器", "cloudflared" to "Cloudflare 隧道",
            "frp_tunnel" to "FRP 隧道",
            "cf_route_hint" to "Cloudflare 隧道的路由（Public Hostname / 自定义域名）只能在 Cloudflare 官网控制面板中配置，App 仅负责运行隧道连接。",
            "cf_token" to "Cloudflare Token", "cf_hint" to "输入 Cloudflare 隧道 Token",
            "cf_connecting" to "连接中...", "cf_connected" to "已连接", "cf_disconnected" to "未连接", "cf_settings" to "Cloudflare 隧道", "cf_enable" to "启用",
            "auto_start_frp" to "开机自启 FRP", "auto_start_cf" to "开机自启 Cloudflare",
            "cf_token_desc" to "请在配置页填写 Cloudflare 隧道 Token",
            "name" to "名称", "session" to "会话", "today" to "今日",
        )

        val enMap: Map<String, String> = mapOf(
            "home" to "Home", "config" to "Config", "overview" to "Overview", "log" to "Log",
            "settings" to "Settings", "running" to "Running", "stopped" to "Stopped", "start" to "Start",
            "stop" to "Stop", "server" to "FRP Server", "address" to "Address", "port" to "Port",
            "token" to "Token", "token_opt" to "Token (optional)", "user" to "User", "user_opt" to "User (optional)",
            "proxies" to "Proxies", "visitors" to "Visitors", "add" to "Add", "no_proxy" to "No proxies",
            "no_visitor" to "No visitors", "visitor_hint" to "Access stcp/xtcp? Add it under Visitors",
            "add_hint" to "Tap the + button to add", "auto_start" to "Auto Start", "language" to "Language",
            "english" to "English", "clear" to "Clear", "type" to "Type", "local_ip" to "Local IP",
            "local_port" to "Local Port", "remote_port" to "Remote Port", "cancel" to "Cancel",
            "add_proxy" to "Add Proxy", "add_visitor" to "Add Visitor", "output" to "Output",
            "launcher" to "FrpDroid", "tap_start" to "Tap to start", "version" to "Version",
            "about" to "About", "notif" to "Notification", "notif_on" to "Enable notification",
            "theme" to "Dark theme",
            "import" to "Import", "export" to "Export", "export_ok" to "Config exported to",
            "import_ok" to "Config imported", "import_fail" to "Invalid or unreadable config",
            "secret_key" to "Secret Key", "custom_domains" to "Custom Domains", "multiplexer" to "Multiplexer",
            "server_name" to "Server Name", "bind_addr" to "Bind Address", "bind_port" to "Bind Port",
            "fallback_to" to "Fallback visitor", "fallback_timeout" to "Fallback timeout (ms)",
            "keep_open" to "Keep Tunnel Open", "plugin" to "Plugin", "unix_path" to "Unix Socket Path",
            "local_path" to "Local Path", "strip_prefix" to "Strip Prefix", "http_user" to "HTTP User",
            "http_password" to "HTTP Password", "local_addr" to "Local Address", "crt_path" to "Cert Path",
            "key_path" to "Key Path", "host_rewrite" to "Host Rewrite", "req_headers" to "Headers(k=v)", "metadatas" to "Metadatas(k=v) (optional)",
            "tcp" to "TCP", "udp" to "UDP", "http" to "HTTP", "https" to "HTTPS", "tcpmux" to "TCPMux",
            "stcp" to "STCP", "xtcp" to "XTCP", "none" to "None", "unix_domain_socket" to "Unix Socket",
            "static_file" to "Static File", "https2http" to "HTTPS→HTTP", "proxy_tab" to "Proxy",
            "visitor_tab" to "Visitor", "save" to "Save", "no_logs" to "No logs", "traffic" to "Traffic",
            "download" to "Download", "upload" to "Upload", "reset" to "Reset", "ok" to "OK",
            "author" to "Author", "frp_version" to "frp version", "cf_version" to "Cloudflare version",
            "saved" to "Saved", "edit_proxy" to "Edit Proxy", "edit_visitor" to "Edit Visitor",
            "select_server" to "Select Server", "new_server" to "New Server", "server_label" to "Server Name",
            "current_server" to "Current Server", "delete_server" to "Delete", "rename_server" to "Rename Server",
            "import_as_new" to "Import as new server", "import_overwrite" to "Overwrite current server",
            "cloudflared" to "Cloudflare Tunnel", "frp_tunnel" to "FRP Tunnel",
            "cf_route_hint" to "Cloudflare tunnel routes (Public Hostname / custom domains) can only be configured in the Cloudflare dashboard. This app only runs the tunnel connection.",
            "cf_token" to "Cloudflare Token", "cf_hint" to "Enter Cloudflare tunnel token",
            "cf_connecting" to "Connecting...", "cf_connected" to "Connected", "cf_disconnected" to "Not connected",
            "cf_settings" to "Cloudflare Tunnel", "cf_enable" to "Enable", "auto_start_frp" to "Auto-start FRP",
            "auto_start_cf" to "Auto-start Cloudflare",
            "cf_token_desc" to "Enter your Cloudflare tunnel token in Settings",
            "name" to "Name", "session" to "Session", "today" to "Today",
        )
    }
}

/** 取词：优先中文，回退英文，最后回退 key 本身 */
fun T.str(k: String): String = zh[k] ?: en[k] ?: k
